[package]
name = "zk-regex-compiler"
version = "1.1.0"
authors = [
    "Javier Su <javier.su.weijie@gmail.com>",
    "Kata Choi <kata.choi@gmail.com>",
    "Sora Suegami <suegamisora@gmail.com>",
    "Yush G <aayushg@mit.edu>",
]
license = "MIT"
edition = "2018"
# exclude = ["index.node"]

[[bin]]
name = "zk-regex"
path = "src/bin/compiler.rs"

[lib]
crate-type = ["rlib", "cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tabbycat = { version = "0.1", features = ["attributes"], optional = true }
fancy-regex = "0.11.0"
petgraph = "0.6.3"
graph-cycles = "0.1.0"
thiserror = "1.0.40"
serde_json = "1.0.95"
serde = { version = "1.0.159", features = ["derive"] }
itertools = "0.10.3"
clap = { version = "=4.2.1", features = ["derive"] }
ahash = "=0.8.7"
regex-automata = "0.4.5"
regex = "1.10.3"
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.neon]
version = "0.10"
default-features = false
features = ["napi-6"]

[features]
default = ["export_neon_main"]
export_neon_main = []
