[package]
name = "zk-regex-compiler"
version = "2.1.1"
authors = [
    "Javier Su <javier.su.weijie@gmail.com>",
    "Kata Choi <kata.choi@gmail.com>",
    "Sora Suegami <suegamisora@gmail.com>",
    "Yush G <aayushg@mit.edu>",
    "Aditya Bisht <adityabisht64@gmail.com>",
]
license = "MIT"
edition = "2018"

[[bin]]
name = "zk-regex"
path = "src/bin/compiler.rs"

[lib]
crate-type = ["rlib", "cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tabbycat = { version = "0.1", features = ["attributes"], optional = true }
fancy-regex = "=0.13.0"
petgraph = "0.6.3"
graph-cycles = "0.1.0"
thiserror = "1.0.40"
serde_json = "1.0.95"
serde = { version = "1.0.159", features = ["derive"] }
itertools = "0.13.0"
clap = { version = "=4.2.1", features = ["derive"] }
ahash = "=0.8.11"
regex-automata = "=0.4.7"
regex = "=1.10.6"
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2"
serde-wasm-bindgen = "0.6.5"
